/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'
import { useVideoTexture } from '@react-three/drei'

function DemoConsole(props) {
  const { nodes, materials } = useGLTF('/models/demo-console.glb');

  
  const txt = useVideoTexture(props.texture ? props.texture : '/textures/project/project1.mp4');
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={46.115}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane.geometry}
          material={nodes.Plane.material}
          position={[0, -0.031, 0.045]}
          rotation={[0, Math.PI, 0]}
          scale={-0.2}
        >
          <meshStandardMaterial map={txt} toneMapped={false} />
        </mesh>
        
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.RETROID1_RTR_MAT_0.geometry}
          material={materials.RTR_MAT}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.1}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/demo-console.glb')

export default DemoConsole;